# Collector specific configuration
API_URL: "https://dtmapi.iom.int/api/IdpAdmin{admin_level}Data/GetAdmin{admin_level}Datav2?Admin0Pcode={iso3}"
tags:
  - conflict-violence
  - displacement
  - forced displacement
  - hxl
  - internally displaced persons-idp
