# Collector specific configuration
API_URL: "https://dtmapi.iom.int/api/IdpAdmin{admin_level}Data/GetAdmin{admin_level}Datav2?Admin0Pcode={iso3}"
tags:
  - conflict-violence
  - displacement
  - forced displacement
  - hxl
  - internally displaced persons-idp
resource_filename: global-iom-dtm-from-api-admin{admin_level}.csv
resource_data:
  name: Global IOM DTM data admin {admin_level}
  description: >-
    Global IOM displacement tracking matrix data
    at the admin {admin_level} level, sourced from the DTM API
qc_indicators:
  - code: "HTI"
    title: "Haiti"
    unit: "Number of IDPs"
    description: "Number of IDPs in Haiti over time"
    code_col: "#country+code"
    value_col: "#affected+idps"
    date_col: "#date+reported"
  - code: "IRQ"
    title: "Iraq"
    unit: "Number of IDPs"
    description: "Number of IDPs in Iraq over time"
    code_col: "#country+code"
    value_col: "#affected+idps"
    date_col: "#date+reported"
  - code: "SDN"
    title: "Sudan"
    unit: "Number of IDPs"
    description: "Number of IDPs in Sudan over time"
    code_col: "#country+code"
    value_col: "#affected+idps"
    date_col: "#date+reported"
quickcharts:
  hashtag: "#country+code"
  numeric_hashtag: "#affected+idps"
  cutdown: 2
  cutdownhashtags:
    - "#country+code"
    - "#date+reported"
    - "#affected+idps"
  date_format: "%Y-%m-%dT%H:%M:%S"
admin_levels:
  - 0
  - 1
  - 2
hxl_tags:
  id: "#id+code"
  operation: "#operation+name"
  admin0Name: "#country+name"
  admin0Pcode: "#country+code"
  admin1Name: "#adm1+name"
  admin1Pcode: "#adm1+code"
  admin2Name: "#adm2+name"
  admin2Pcode: "#adm2+code"
  numPresentIdpInd: "#affected+idps"
  reportingDate: "#date+reported"
  yearReportingDate: "#date+year+reported"
  monthReportingDate: "#date+month+reported"
  roundNumber: "#round+code"
  assessmentType: "#assessment+type"
