# Collector specific configuration
IDPS_URL: "https://dtmapi.iom.int/api/IdpAdmin{admin_level}Data/GetAdmin{admin_level}Datav2?Admin0Pcode={iso3}"
COUNTRIES_URL: "https://dtmapi.iom.int/api/Common/GetAllCountryList"
tags:
  - conflict-violence
  - displacement
  - forced displacement
  - hxl
  - internally displaced persons-idp
resource_filename: global-iom-dtm-from-api-admin-0-to-2.csv
resource_data:
  name: Global IOM DTM data for admin levels 0-2
  description: >-
    Global IOM displacement tracking matrix data
    at admin levels 0, 1, and 2, sourced from the DTM API
qc_resource_filename: data_for_quickcharts.csv
qc_resource_data:
  name: Data for QuickCharts
  description: Filtered and aggregated data used to create QuickCharts
qc_indicators:
  - code: "HTI"
    title: "Haiti"
    unit: "Number of IDPs"
    description: "Number of IDPs in Haiti per year"
    code_col: "#country+code"
    value_col: "#affected+idps"
    date_col: "#date+year+reported"
  - code: "IRQ"
    title: "Iraq"
    unit: "Number of IDPs"
    description: "Number of IDPs in Iraq per year"
    code_col: "#country+code"
    value_col: "#affected+idps"
    date_col: "#date+year+reported"
  - code: "SDN"
    title: "Sudan"
    unit: "Number of IDPs"
    description: "Number of IDPs in Sudan per year"
    code_col: "#country+code"
    value_col: "#affected+idps"
    date_col: "#date+year+reported"
quickcharts:
  hashtag: "#country+code"
  numeric_hashtag: "#affected+idps"
  cutdown: 0
admin_levels:
  - 0
  - 1
  - 2
hxl_tags:
  id: "#id+code"
  operation: "#operation+name"
  admin0Name: "#country+name"
  admin0Pcode: "#country+code"
  admin1Name: "#adm1+name"
  admin1Pcode: "#adm1+code"
  admin2Name: "#adm2+name"
  admin2Pcode: "#adm2+code"
  numPresentIdpInd: "#affected+idps"
  reportingDate: "#date+reported"
  yearReportingDate: "#date+year+reported"
  monthReportingDate: "#date+month+reported"
  roundNumber: "#round+code"
  assessmentType: "#assessment+type"
