line-length = 79
exclude = ["_version.py"]

[lint]
# List of rules: https://docs.astral.sh/ruff/rules/
select = [
  "E",   # pycodestyle - default
  "F",   # pyflakes - default
  "I"    # isort
]

[lint.isort]
known-local-folder = ["hdx.scraper.dtm"]
known-third-party = ["hdx.api", "hdx.utilities", "hdx."]
